version: "3.9"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'market_username'
      POSTGRES_PASSWORD: 'market_password'
      POSTGRES_DB: 'marke_db'
      DATABASE_HOSTNAME: 'market_username'
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/market
    ports:
    - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db