# Generated by Django 3.2.13 on 2023-06-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_verifyphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifyPhone',
            new_name='PhoneVerification',
        ),
    ]
